### ISSUE TITLE
eval of plot returns "gtk initialization" error

### ISSUE THREAD

**Issue by stchang** [stchang/pasterack#2]
For example:
# lang racket   ; draw a graph of cos

(require plot) ; and deriv^3(cos)
(define ((deriv f) x)
  (/ (- (f x) (f (- x 0.001))) 0.001))
(define (thrice f) (lambda (x) (f (f (f x)))))
(plot (list (function ((thrice deriv) sin) -5 5)
            (function cos -5 5 #:color 'blue)))

gives error Gtk initialization failed for display "0"

Maybe related to Racket PR12465?

**Comment by jbclements** [comment]
@stchang I have a student now seeing this error. Can you elaborate on how it was fixed?

**Comment by stchang** [comment]
> ... oh wait... was this a problem that you saw on a headless machine?

Yes, anything that uses `racket/gui` will produce this problem. See PR12465.

If you `(require plot/pict)`, it won't pull in `racket/gui`.
