### ISSUE TITLE
Issue with the IRC alerting?

### ISSUE THREAD

**Issue by jarcane** [stchang/pasterack#42]
For some days now whenever I have attempted to use the 'Alert channel' option on pasterack.org I get the following:
```
Exception
The application raised an exception with the message:

tcp-write: error writing
  system error: Broken pipe; errno=32

Stack trace:
<empty box appears here>
```
The paste is still added to the list, and I can access it by backing up to the main page and looking at the top link in the queue, generally, but no channel alert is sent.

**Comment by stchang** [comment]
Fixed after restarting the server.
