### ISSUE TITLE
Pasterack breaks for this program

### ISSUE THREAD

**Issue by soegaard** [stchang/pasterack#64]
Hi,

For some reason, this program provokes an error on Pasterack:

```
#lang racket
(define S '(A B C D))
(for* ([a S] [b S] [c S] [d S] [e S])
  (displayln (map ~a '(1 2 3 4 5) (list a b c d e))))
```

The output contains 1024 lines - but by rewriting the program I can see that ought not be a problem.

![image](https://user-images.githubusercontent.com/461765/96743417-45c52d80-13c4-11eb-9452-4b706f01ae4a.png)

**Comment by stchang** [comment]
fixed thanks http://pasterack.org/pastes/12770
