### ISSUE TITLE
Add oEmbed / OpenGraph tags for description, image

### ISSUE THREAD

**Issue by spdegabrielle** [stchang/pasterack#70]
https://racket.discourse.group/t/link-preview-did-not-render-for-twitch-racket-livestream-link/96/3?u=spdegabrielle

error on Discourse when discourse attempts to render a preview from pasterack: 
> oEmbed / OpenGraph tags could not be found: description, image

- https://oembed.com
- https://ogp.me

Might be fun to see if I can get http://pasterack.org/pastes/29314 to render code + fish

I think I need to mess with these lines: https://github.com/stchang/pasterack/blob/1e4e2cc31e873044e76e329d42761363a9875fa2/pasterack.rkt#L709

(assign to me if you like)

**Comment by stchang** [comment]
I dont know anything about oembed but would this be a feature that would be better added directly to the racket web server? (or as a web server library?)

**Comment by spdegabrielle** [comment]
probably, but it seems quite task specific.


probably a bigger task than I  first considered. 

- [ ] dispatcher detects embed request
- [ ] oembed module asks application for content
- [ ] embed returns json including iframe for code


https://meta.discourse.org/t/embedding-pens-from-codepen/13578/17
